name: scarlet_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  geolocator: ^11.0.0
  google_maps_flutter: ^2.5.3
  http: ^1.1.0
  intl: ^0.18.1
  json_serializable: ^6.7.1
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/img/logos/
    - assets/img/icons/
