// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZtpEewWIlgxUmsw4dDQV_OR6vdL1Bhnw',
    appId: '1:10302514103:web:ddbe2fb29e3374460cbe32',
    messagingSenderId: '10302514103',
    projectId: 'scarlet-419401',
    authDomain: 'scarlet-419401.firebaseapp.com',
    databaseURL: 'https://scarlet-419401-default-rtdb.firebaseio.com',
    storageBucket: 'scarlet-419401.appspot.com',
    measurementId: 'G-E8TXN70XJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWvhyn1oJYFCdyWOfaXCFY842_bcp5Tlw',
    appId: '1:10302514103:android:73974b7324ff6ff90cbe32',
    messagingSenderId: '10302514103',
    projectId: 'scarlet-419401',
    databaseURL: 'https://scarlet-419401-default-rtdb.firebaseio.com',
    storageBucket: 'scarlet-419401.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgZawP9DTTQsn9PAJ_6OiAG3nhKJ27ZjM',
    appId: '1:10302514103:ios:94bd7e85f0dcb2c40cbe32',
    messagingSenderId: '10302514103',
    projectId: 'scarlet-419401',
    databaseURL: 'https://scarlet-419401-default-rtdb.firebaseio.com',
    storageBucket: 'scarlet-419401.appspot.com',
    iosBundleId: 'com.example.scarletApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgZawP9DTTQsn9PAJ_6OiAG3nhKJ27ZjM',
    appId: '1:10302514103:ios:94bd7e85f0dcb2c40cbe32',
    messagingSenderId: '10302514103',
    projectId: 'scarlet-419401',
    databaseURL: 'https://scarlet-419401-default-rtdb.firebaseio.com',
    storageBucket: 'scarlet-419401.appspot.com',
    iosBundleId: 'com.example.scarletApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZtpEewWIlgxUmsw4dDQV_OR6vdL1Bhnw',
    appId: '1:10302514103:web:ac25188f4cdfe6520cbe32',
    messagingSenderId: '10302514103',
    projectId: 'scarlet-419401',
    authDomain: 'scarlet-419401.firebaseapp.com',
    databaseURL: 'https://scarlet-419401-default-rtdb.firebaseio.com',
    storageBucket: 'scarlet-419401.appspot.com',
    measurementId: 'G-EKSJJY8LLP',
  );
}
